spring:
  application:
    name: admin-server
server:
  port: 8888
eureka:
  instance:
    lease-expiration-duration-in-seconds: 60  # 续约到期时间（默认90秒）
    lease-renewal-interval-in-seconds: 20 # 续约更新时间间隔（默认30秒）
  client:
    healthcheck:
      enabled: true	# 开启健康检查（需要spring-boot-starter-actuator依赖）
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
