mybatis:
  config-location: classpath:/mybatis-config.xml

spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://10.186.28.24:8066/TESTDB?useUnicode=true&characterEncoding=utf-8
    username: root
    password: 123456
    initialSize: 5
    minIdle: 5
    maxActive: 200
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 120000 
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 from cx_bas_staff
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    filters: stat,wall,log4j
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis= 5000
    
redis:
  cache:
    maxIdle: 50
    maxTotal: 100
    testOnBorrow: true
    testOnReturn: false
    timeBetweenEvictionRunsMillis: 60000
    testWhileIdle: true
    jedisClusterNodes: 172.30.105.83:9001,172.30.105.83:9002,172.30.105.83:9003,172.30.105.83:9004,172.30.105.83:9005,172.30.105.83:9006
    connectionTimeOut: 3000
    soTimeOut: 3000
    maxRedirections: 5
